### PR TITLE
feat: release 9.0.0-alpha2

### PR DESCRIPTION
**Pull request by CesarLiu**
- apollo rules replace native bazel rules
- merge the target of the module
- bugs fix

Change-Id: I2093de61f339bd7f73439d5c8257894630eff759

### CODE REVIEW

**Comment by usrn1** [comment]
when i pull the images,there are some problems.
Error response from daemon: manifest for apolloauto/apollo:dev-aarch64-18.04-20230828_1510 not found: manifest unknown: manifest unknown</pre>

**Comment by CesarLiu** [comment]
Hi! thanks for checking my updates there. You're right! That docker image is built by myself, I haven't uploaded it to dockerhub, and I can not push it to apollo's official dockerhub. I have built it only for jetson tx2, pls. make sure if you are in the same case. If not, just refer to the office one for jetson orin, can delete libtorch installed there and install it through source. check install_libtorch.sh!

**Comment by usrn1** [comment]
I also use the tx2.if it is convenient,could you upload the docker images to dockerhub。I am a rookie and want to deploy it on my jetson tx2. Thank you very much!

---- Replied Message ----
| From | Xiang ***@***.***> |
| Date | 09/07/2023 22:27 |
| To | CesarLiu/apollo ***@***.***> |
| Cc | liang ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [CesarLiu/apollo] feat: release 9.0.0-alpha2 (PR #3) |

Hi! thanks for checking my updates there. You're right! That docker image is built by myself, I haven't uploaded it to dockerhub, and I can not push it to apollo's official dockerhub. I have built it only for jetson tx2, pls. make sure if you are in the same case. If not, just refer to the office one for jetson orin, can delete libtorch installed there and install it through source. check install_libtorch.sh!

**Comment by CesarLiu** [comment]
my docker image is here: docker pull cesarliu/apollo:dev-aarch64-tx2-18.04-20230908_1330. don't hesitate to leave a star for my fork!

**Comment by CesarLiu** [comment]
did you try out the scripts to build your own image?

**Comment by usrn1** [comment]
Yes,but there are also some error,

**Comment by usrn1** [comment]
Do you upload the images? I don't pull your images successfully.

**Pull request closed without merging**
